---
extends: standard

env:
  browser: true
  es6: true
  jquery: true

parserOptions:
  sourceType: script

rules:
  no-irregular-whitespace:
    - error
    - skipRegExps: true
  space-before-function-paren:
    - error
    - never
