---
extends: standard

env:
  commonjs: false
  node: false

globals:
  # window globals
  URL: false
  clearInterval: false
  clearTimeout: false
  console: false
  location: false
  setInterval: false
  setTimeout: false

rules:
  comma-dangle:
    - off
  linebreak-style:
    - error
    - unix
  no-case-declarations:
    - error
  no-console:
    - warn
  no-empty:
    - error
  no-extra-semi:
    - error
  no-irregular-whitespace:
    - error
    - skipRegExps: true
  no-unused-labels:
    - error
  object-curly-spacing:
    - warn
    - always
  prefer-const:
    - error
  require-yield:
    - error
  space-before-function-paren:
    - error
    - never
  strict:
    - error
