---
extends:
  - standard
  - prettier

plugins:
  - prettier

env:
  commonjs: false
  node: false

globals:
  # window globals
  URL: false
  clearInterval: false
  clearTimeout: false
  console: false
  location: false
  setInterval: false
  setTimeout: false

rules:
  prettier/prettier:
    - warn
    - semi: false
      singleQuote: true

  no-case-declarations:
    - error
  no-console:
    - warn
  no-empty:
    - error
  no-irregular-whitespace:
    - error
    - skipRegExps: true
  no-unused-labels:
    - error
  object-curly-spacing:
    - warn
    - always
  prefer-const:
    - error
  require-yield:
    - error
  sort-imports:
    - warn
    - ignoreCase: true
  strict:
    - error
